### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by grahamrhay**
Added caveat for packaging to README.

### CODE REVIEW

**Comment by driskell** [comment]
Sorry if you considered this already!

Why not just put the code in a directory in the repository? Makes it tidier and means no need for this caveat.

**Comment by grahamrhay** [comment]
do you mean moving all the go files into a subfolder called logstash-forwarder in the repo?

**Comment by driskell** [comment]
Yes that would work.

Or if you follow Go toolset defaults, into a "src/logstash-forwarder" folder. Setting GOPATH to repo root you can then run "go install logstash-forwarder" and it'll drop the binary into "bin".

**Comment by driskell** [comment]
All down to preference but certainly a folder might make it more intuitive. I guess as well not many users are going to be using Jenkins so is it more internal documentation? Just a thought!

**Comment by grahamrhay** [comment]
the point is that if you use jenkins, then it will by default use a folder named workspace. whichever solution you use, you will need to do *something* different. I was just trying to save someone else the pain I went through this morning. if you don't want it in the readme, that's not a problem, feel free to close this PR

**Comment by jordansissel** [comment]
I don't think this is the right solution. `go build -o logstash-forwarder` works to force the binary name. I'll update the readme accordingly.

**Comment by jordansissel** [comment]
> if you use jenkins, then it will by default use a folder named workspace

I use jenkins for testing lsf, and I don't have it cloning the logstash-forwarder repo directly into workspace, I Just use the git clone as normal and it puts it in workspace/logstash-forwarder/ .... I don't know what you are doing to cause this, sorry :\

The update I will make to the readme should solve this for you.

**Comment by grahamrhay** [comment]
hmm, interesting. all my jenkins jobs use git, and they all go directly into a folder called workspace inside the job folder. I've never seen any other behaviour. I wonder what we're doing different?

**Comment by grahamrhay** [comment]
image

**Comment by jordansissel** [comment]
Thanks for helping make logstash-forwarder better!

Logstash-forwarder is going away and is replaced by https://github.com/elastic/filebeat/. If this is still an issue with filebeat, would you mind opening a ticket [there](https://github.com/elastic/filebeat/issues)?

**Pull request closed without merging**
