### PR TITLE
Config environment variables support

### PR DESCRIPTION
**Pull request by zhekanax**

### CODE REVIEW

**Comment by driskell** [comment]
Wow so simple. Should definitely update docs though as well.

IMO though it's better to keep everything in the config. Having expansion like this just means engineers start to spread configuration across even more files than if it were just a single config file. Means you can't just "look at the live config" - you need to "decipher the live config". Configuration management should also mean this is not required as the parameters can be expanded when applied. Of course there's always edge cases where it benefits. Just my two cent. :+1:

**Comment by zhekanax** [comment]
Yep, it can be a controversial feature, but I needed it really hard running forwarder in docker containers and multiple deployment stages. And each stage, of course, has it own logstash server.

**Comment by zhekanax** [comment]
Updated README

**Comment by pnegahdar** [comment]
Status on this?

**Comment by jordansissel** [comment]
While I am not a fan of having two kinds of configuration sources at run-time (environment variables and config files), given the simplicity of this change combined with how frequently it is requested, I am willing to accept the feature.

**Comment by lomdalf** [comment]
Could you please let us know when this change will be available in the apt-get repo? We really need this feature and were wondering if we should implement our own solution OR wait for this to be available.

**Comment by jordansissel** [comment]
@lomdalf I don't know when the next release is planned, but we don't have any secret tools that build logstash-forwarder. From a git clone, 'make deb` should produce a deb package for you.

**Comment by lomdalf** [comment]
Sweet! Thank you very much!!

**Pull request closed without merging**
