### PR TITLE
registry rotation on Windows fails

### PR DESCRIPTION
**Pull request by justmara**
this is fix for #270

### CODE REVIEW

**Comment by justmara** [comment]
ouch, cla checks. signed now, sry 8)

**Comment by bradvido** [comment]
I have this issue on windows as well. I'm assuming it affects all windows users. 
Testing confirms this PR fixes it; when can it get merged? Was hoping for it to be fixed in the 0.4.0 release yesterday, but no luck :-/

**Comment by alfeg** [comment]
We were forced to build from source and merge pull-request manually. I there any reasons not to merge?

**Comment by sebaaa** [comment]
I agree .logstash-forwarder needs to be explicitly closed. 

What's the point of renaming .logstash-forwarder to .logstash-forwarder.old before renaming .logstash-forwarder.new to .logstash-forwarder ?

The registrar_other.go doesn't do this.

**Comment by driskell** [comment]
@sebaa Windows won't allow you to "move" a file if the destination already exists. POSIX systems will simply overwrite the destination. Thus for Windows the destination file needs removing. This would mean removing ".logstash-forwarder" - if a crash happens between doing this and putting the new file in place, there's going to be a problem. This I think is why the author renames to .old. Admittedly though they don't check for .old during startup and probably should, to detect the crash event.

**Comment by sebaaa** [comment]
@driskell Well, I guess it depends on which API GO uses for the Rename operation. MoveFileEx() will overwrite if you ask it to :)

But your reasoning that doing a rename instead of a delete of ".logstash-forwarder" makes good sense if something explodes before (or during) the renaming of ".logstash-forwarder.new" to ".logstash-forwarder". (except that the .old is never deleted, but I guess that 's part of the original ticket).

**Comment by adriaangraas** [comment]
Does anyone have an idea of how long it is going to take before the fix is being released? AFAIC this is concerning all users that have Windows servers.

**Comment by jeybonnet** [comment]
When is that going to be merged to master?

**Comment by mauriceteunissen** [comment]
Been running this in production for a few weeks now without a hitch, would be nice if it could be merged to master

**Comment by mkuzmin** [comment]
@justmara could you rebase the PR please, it started raising merge conflicts

**Comment by justmara** [comment]
@mkuzmin tried making rebase - now it looks strange - like if all the other commits added to this PR. looks like id I did something wrong =)

**Comment by driskell** [comment]
I think you rebased master onto your branch, rather than your branch onto master or something :) Might want to reset back to your last commit.

The way I would do it: Setup a remote for "upstream" pointing to elastic/logstash-forwarder repository. Then checkout your master with your commits. Then hit `git rebase upstream/master` - and then force push `git push -f`

**Comment by justmara** [comment]
@driskell yey! thanks, much better now 8)

**Comment by toebens** [comment]
it is working. 

please accept pull request

**Comment by darkoz** [comment]
Is there any plan to merge this?

**Comment by radiumx3** [comment]
Is there any plan to merge this?

**Comment by aditya0224** [comment]
I still see the problem, after i pull the latest for this? is it merged?

**Comment by ktodyruik** [comment]
Has this project died? This issue is a year old and people have been asking
about merging this for quite a while.

**Comment by alfeg** [comment]
It's a shame for project, but we opt out to not use logstash at all. Using logstash to forward all logs.

**Comment by ruflin** [comment]
This fix will go directly into filebeat, the future replacement of logstash-forwarder.

**Comment by ruflin** [comment]
@justmara Do you prefer to open a pull request with the change on filebeat (https://github.com/elastic/filebeat) or should we copy over fix?

**Comment by justmara** [comment]
@ruflin seriously? you've made new repo with **copy** of this master branch (not even the fork!)? so logbeat is simply '_rename and history whipe_'?

**Comment by ruflin** [comment]
@justmara The logstash-forwarder repository was split up in two parts. Parts of the code went into filebeat, parts into libbeat to structure it as a beat. In both cases the code was heavily restructured. 
The first part of your change would still apply to the registrar.go file here: https://github.com/elastic/filebeat/blob/master/beat/registrar.go#L75 The second part can now be found in filecompare_windows.go here: https://github.com/elastic/filebeat/blob/master/input/filecompare_windows.go#L25

**Comment by ruflin** [comment]
This should be fixed in filebeat (next version of logstash-forwarder) with https://github.com/elastic/filebeat/pull/43 and https://github.com/elastic/filebeat/pull/45

**Comment by ruflin** [comment]
As the next release of logstash-forwarder will be [filebeat](https://github.com/elastic/filebeat), I will close this issue based on the comment above. In case the issue still exists in filebeat, please reopen or open a new issue directly in the filebeat repo.

**Pull request closed without merging**
