### PR TITLE
Corrected record offset sent via lumberjack.

### PR DESCRIPTION
**Pull request by cdahlqvist**
Updated the log harvester to ensure a unique offset is sent in the event for every line.

### CODE REVIEW

**Comment by webmat** [comment]
Looks like this fix is in place in master: https://github.com/elasticsearch/logstash-forwarder/blob/a718299722376cf84b4ebd652586eada2af0e2f3/harvester.go#L81

**Comment by ayashjorden** [comment]
HI all, 
I'm getting a similar behavior from my LSF instance, not picking up files after they're being truncated.
Is there a timeframe for this PR to be merged? or there's another solution (which I didn't find :))

Thanks,
Yarden

**Comment by driskell** [comment]
@ayashjorden this PR is redundant and should really be closed - the issue is already fixed in master (it was fixed by alphazero a while back in a cleanup branch, and eventually merged in.)
If you're having issues it's unrelated to this.

**Comment by alphazero** [comment]
Hi Jason,

I have not been involved with ES since Sept 2, 2015. Confidentially and 
just FYI.

/R

**Pull request closed without merging**
