### PR TITLE
Grammar

### PR DESCRIPTION
**Pull request by failshell**
Might as well use proper French :)

### CODE REVIEW

**Comment by flmessier** [comment]
:+1:

**Comment by Typositoire** [comment]
:+1:

**Comment by webmat** [comment]
:100:

**Comment by driskell** [comment]
:+1:

**Comment by ph** [comment]
Hello Lightspeed.

**Comment by colinsurprenant** [comment]
lol
LGTM

**Comment by colinsurprenant** [comment]
WHO WROTE THAT? ;)

**Comment by ph** [comment]
I did, but you also did a review

**Comment by colinsurprenant** [comment]
cassé!

**Comment by jordansissel** [comment]
(I edited the commit message to remove the nazi reference)

Thanks for fixing the spelling :)

**Pull request closed without merging**
